In [1]:
import torch

/home/ronald/.local/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
print(torch.__version__)

1.8.2+cpu


# Tensores PyTorch
Tensores são os tipos de dados fundamentais do PyTorch. Um tensor é uma matriz multidimensional semelhante aos ndarrays de NumPy:

* Um escalar pode ser representado como um tensor de dimensão zero.
* Um vetor pode ser representado como um tensor unidimensional.
* Uma matriz bidimensional pode ser representada como um tensor bidimensional.
* Uma matriz multidimensional pode ser representada como um tensor multidimensional.

In [3]:
# incializando um tensor
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [4]:
# acessando a forma e o tipo do dado;
print(f'Dimensão de x: {x.shape}\nDimensão de y: {y.shape}\n')
print(f'Tipo de dado de x: {x.dtype}\nTipo de dado de y: {y.type}')

Dimensão de x: torch.Size([1, 2])
Dimensão de y: torch.Size([2, 1])

Tipo de dado de x: torch.int64
Tipo de dado de y: <built-in method type of Tensor object at 0x7f94f8ba4ec0>


In [5]:
# verificando um tensor do tipo booleano
x = torch.tensor([False, True])
y = torch.tensor(([False, True, 1, 2.0]))
# se tivermos um tensor somente booleano teremos uma saida diferente se a lista conter outros
# tipos de dados, os valores serão convertidos em 0 -> False e 1 -> True
print(f'Somente booleanos: {x}')
print(f'Diversos tipos de dados: {y}')

Somente booleanos: tensor([False,  True])
Diversos tipos de dados: tensor([0., 1., 1., 2.])


In [6]:
# gerando um tensor de zeros 3 x 4
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# gerando um tensor de uns 3 x 4
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# gerando um tensor aleatorio 3 x 4, com valor minimo 0 e maximo 10
torch.randint(low=0, high=10, size=(3,4))

tensor([[3, 9, 8, 6],
        [0, 4, 4, 5],
        [3, 1, 9, 3]])

In [9]:
# gerando numeros aleatorios entre 0 e 1
torch.rand(3,4)

tensor([[0.7923, 0.8356, 0.2059, 0.1652],
        [0.4776, 0.8677, 0.5965, 0.0793],
        [0.5587, 0.7305, 0.0876, 0.6230]])

In [10]:
# gerando numeros de uma distribuição normal
torch.randn((3,4))

tensor([[-0.0792,  1.1179,  0.3632,  1.0890],
        [-0.4148, -0.5330, -0.7881,  0.8784],
        [ 0.2617, -0.4409,  0.3131, -1.6639]])

In [11]:
# convertendo uma matriz Numpy em um tensor
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(f'Tipo de dado: {type(x)}, tipo anterior convertido {type(y)}')

Tipo de dado: <class 'numpy.ndarray'>, tipo anterior convertido <class 'torch.Tensor'>


# Operações com tensores

In [12]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(f'Tensor com valores iniciais: {x}')
print(f'Tensor com valores multiplicados por 10: {x*10}')

Tensor com valores iniciais: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Tensor com valores multiplicados por 10: tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


In [13]:
# adicionando valor ao tensor
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [14]:
# concatenando tensores
x = torch.randn(10,10,10)
z = torch.cat([x,x], axis=0)
print('Eixo cat axis 0: ', x.shape, z.shape)

z = torch.cat([x,x], axis=1)
print('Eixo cat axis 1: ', x.shape, z.shape)

z = torch.cat([x,x], axis=2)
print('Eixo cat axis 2: ', x.shape, z.shape)

Eixo cat axis 0:  torch.Size([10, 10, 10]) torch.Size([20, 10, 10])
Eixo cat axis 1:  torch.Size([10, 10, 10]) torch.Size([10, 20, 10])
Eixo cat axis 2:  torch.Size([10, 10, 10]) torch.Size([10, 10, 20])


In [15]:
x = torch.arange(25).reshape(5,5)
print(x)
print(f'Maior valor no tensor: {x.max()}')
print(f'Menor valor no tensor: {x.min()}')

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
Maior valor no tensor: 24
Menor valor no tensor: 0


In [16]:
# extraindo os maiores valores do tensor e sua localização/indice (linha da matriz)
x.max(dim=0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

É importante saber que você pode fazer quase todas as operações do NumPy no PyTorch com quase a mesma sintaxe do NumPy. Operações matemáticas padrão, tais como abs, add, argsort, ceil, floor, sin, cos, tan, cumsum, cumprod, diag, eig, exp, log, log2, log10, mean, median, mode, resize, round, sigmoid, softmax, square, sqrt, svd, e transpose, para citar alguns, pode ser diretamente chamado em qualquer tensor com ou sem eixos onde aplicável. Você sempre pode executar dir(torch.Tensor) para ver todos os métodos possíveis para um tensor de tocha ehelp(torch.Tensor.<method>) para consultar a ajuda e a documentação oficial desse método.

# Gradientes automáticos de objetos tensores

In [17]:
# definindo um gradiente e um tensor
x = torch.tensor([[2.,-1.],[1.,1.]], requires_grad=True)
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


No código anterior, o requires_grad parâmetro especifica que o gradiente deve ser calculado para o objeto tensor.

# Construindo uma rede neural usando PyTorch
No capítulo anterior, aprendemos como construir uma rede neural do zero, onde os componentes de uma rede neural são os seguintes:

* O número de camadas ocultas
* O número de unidades em uma camada oculta
* Funções de ativação realizadas nas várias camadas
* A função de perda que tentamos otimizar para
* A taxa de aprendizagem associada à rede neural
* O tamanho do lote de dados aproveitado para construir a rede neural
* O número de épocas de propagação para frente e para trás

In [18]:
import torch
x = torch.rand(1, 6400)
y = torch.rand(6400, 5000)

In [19]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [21]:
x, y = x.to(device), y.to(device)

In [22]:
%timeit z=(x@y)

70.6 ms ± 10.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
x, y = x.cpu(), y.cpu()
%timeit z=(x@y)

83.2 ms ± 10.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
import numpy as np
x = np.random.random((1, 6400))
y = np.random.random((6400, 5000))
%timeit z = np.matmul(x,y)

111 ms ± 13.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
# definindo valores de entrada e saida
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]

Observe que na inicialização da variável de entrada e saída anterior, a entrada e a saída são uma lista de listas em que a soma dos valores na lista de entrada são os valores na lista de saída.

In [26]:
# realizando um cast nas entradas
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

In [27]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
X = X.to(device)
Y = Y.to(device)

In [28]:
# definindo a arquitetura da rede neural
import torch.nn as nn

In [29]:
# criando uma classe para compor a arquitetura de modelo
class MyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__() # chamamos o super para que a classe herde de nn
        self.input_to_hidden_layer = nn.Linear(2,8) # camada linear
        self.hidden_layer_activation = nn.ReLU() # camada de ativação
        self.hidden_to_output_layer = nn.Linear(8,1) # camada linear
        # print(nn.Linear)

In [30]:
print (nn.Linear ( 2 , 7 ))

Linear(in_features=2, out_features=7, bias=True)


In [31]:
def forward (self, x): 
    x = self.input_to_hidden_layer (x) 
    x = self.hidden_layer_activation (x) 
    x = self.hidden_to_output_layer (x) 
    return x

In [32]:
# criando uma instancia
mynet = MyNeuralNet().to(device)

In [33]:
mynet.input_to_hidden_layer.weight

Parameter containing:
tensor([[ 0.4134,  0.5202],
        [ 0.2054, -0.1771],
        [ 0.6796,  0.3176],
        [ 0.1606, -0.1112],
        [-0.2189, -0.1808],
        [-0.1928, -0.5855],
        [ 0.1585,  0.4760],
        [-0.0674,  0.4196]], requires_grad=True)

In [34]:
# Todos os parâmetros de uma rede neural podem ser obtidos usando o seguinte código:
mynet.parameters()

<generator object Module.parameters at 0x7fbcadc844a0>

In [35]:
for i in mynet.parameters():
    print(i)

Parameter containing:
tensor([[ 0.4134,  0.5202],
        [ 0.2054, -0.1771],
        [ 0.6796,  0.3176],
        [ 0.1606, -0.1112],
        [-0.2189, -0.1808],
        [-0.1928, -0.5855],
        [ 0.1585,  0.4760],
        [-0.0674,  0.4196]], requires_grad=True)
Parameter containing:
tensor([ 0.5410,  0.2738,  0.0173,  0.3724,  0.6316, -0.5195,  0.6922,  0.0688],
       requires_grad=True)
Parameter containing:
tensor([[-0.1079,  0.3123, -0.1086, -0.0346, -0.0574, -0.1802, -0.1518, -0.0411]],
       requires_grad=True)
Parameter containing:
tensor([0.0404], requires_grad=True)


# Conjunto de dados, DataLoader e tamanho do lote

In [36]:
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn

In [37]:
x = [[1 , 2], [3 , 4], [5 , 6], [7 , 8]] 
y = [[ 3 ], [ 7 ], [ 11 ], [ 15 ]]

In [38]:
X = torch.tensor (x).float () 
Y = torch.tensor (y).float ()

In [39]:
device = 'cuda' if torch.cuda.is_available () else 'cpu'
X = X.to(device) 
Y = Y.to(device)  

In [40]:
# instanciando uma classe dataset
class Mydataset(Dataset):
    """Definindo metodo que pega pares de entrada e saida
    e converte em objetos flutuantes"""
    def __init__(self, x, y):
        self.x = torch.tensor(x).float()
        self.y = torch.tensor(y).float()

    """Especifica o comprimento do conjunto de entrada de dados"""
    def __len__(self):
        return len(self.x)

    """Método usado para buscar uma linha específica"""
    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]

In [41]:
# criando uma instancia
ds = Mydataset(X, Y)

/tmp/ipykernel_15532/3859479177.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x = torch.tensor(x).float()
/tmp/ipykernel_15532/3859479177.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.y = torch.tensor(y).float()


In [42]:
dl = DataLoader(ds, batch_size=2, shuffle=True)

In [43]:
# abaixo um codigo ilustrativo para impressao de lotes de entrada e saida de dados
for x, y in dl:
    print(x, y)

tensor([[1., 2.],
        [5., 6.]]) tensor([[ 3.],
        [11.]])
tensor([[7., 8.],
        [3., 4.]]) tensor([[15.],
        [ 7.]])


Observe que o código anterior resultou em dois conjuntos de pares de entrada-saída, pois havia um total de quatro pontos de dados no conjunto de dados original, enquanto o tamanho do lote especificado era 2.

In [44]:
# definindo uma classe de rede
class MyNeuralNet (nn.Module): 
    def __init__(self): 
        super().__init__() 
        self.input_to_hidden_layer = nn.Linear (2,8) 
        self.hidden_layer_activation = nn.ReLU () 
        self.hidden_to_output_layer = nn.Linear (8,1) 
    def forward (self, x): 
        x = self.input_to_hidden_layer (x) 
        x = self.hidden_layer_activation (x) 
        x = self.hidden_to_output_layer (x) 
        return x

In [45]:
# definindo o modelo do objeto
mynet = MyNeuralNet().to(device)
loss_func = nn.MSELoss()
from torch.optim import SGD
opt = SGD(mynet.parameters(), lr = 0.001)

In [46]:
# loop pelos lotes de pontos de dados para minimizar o valor de perda
import time
loss_history = []
start = time.time()
for _ in range(50):
    for data in dl:
        x, y = data
        opt.zero_grad()
        loss_value = loss_func(mynet(x), y)
        loss_value.backward()
        opt.step()
        loss_history.append(loss_value)
end = time.time()
print(end - start)

0.30396437644958496


# Previsão de novos pontos de dados

In [47]:
# criando novo ponto de dados para teste de modelo
val_x = [[10,11]]

In [48]:
# realizando um cast nos pontos de dados
val_x = torch.tensor(val_x).float().to(device)

In [49]:
# passando o objeto tensor pela rede neural treinada
mynet(val_x)

tensor([[20.4487]], grad_fn=<AddmmBackward>)

# Implementando uma função de perda personalizada
Em certos casos, podemos ter que implementar uma função de perda customizada para o problema que estamos resolvendo - especialmente em casos de uso complexos envolvendo detecção de objetos / redes adversas geradoras ( GANs ). O PyTorch fornece as funcionalidades para construirmos uma função de perda personalizada, escrevendo uma função nossa.

In [50]:
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch

x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]

X = torch.tensor(x).float()
Y = torch.tensor(y).float()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
X = X.to(device)
Y = Y.to(device) 

class MyDataset(Dataset):
    def __init__(self,x,y):
        self.x = torch.tensor(x).float()
        self.y = torch.tensor(y).float()

    def __len__(self):
        return len(self.x)

    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]

class MyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_to_hidden_layer = nn.Linear(2,8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8,1)

    def foward(self, x):
        x = self.input_to_hidden_layer(x)
        x = self.hidden_layer_activation(x)
        x = self.hidden_to_output_layer(x)
        return x

In [51]:
ds = MyDataset(X, Y)
dl = DataLoader(ds, batch_size=2, shuffle=True)

/tmp/ipykernel_15532/40928522.py:18: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x = torch.tensor(x).float()
/tmp/ipykernel_15532/40928522.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.y = torch.tensor(y).float()


In [52]:
mynet = MyNeuralNet().to(device)

In [53]:
def my_mean_squared_error(_y, y):
    loss = (_y-y)**2
    loss = loss.mean()
    return loss

In [54]:
loss_func = nn.MSELoss()
loss_value = loss_func(mynet(X),Y)
print(loss_value)

NotImplementedError: 

In [55]:
my_mean_squared_error(mynet(X),Y)

NotImplementedError: 

In [56]:
input_to_hidden = mynet.input_to_hidden_layer(X) 
hidden_activation = mynet.hidden_layer_activation (input_to_hidden) 
print(hidden_activation)

tensor([[0.0000, 0.0000, 0.4896, 0.4493, 0.0000, 0.0980, 0.4159, 0.0000],
        [0.0908, 0.1018, 0.3949, 2.0867, 0.0000, 0.0000, 0.5881, 0.0000],
        [0.2633, 0.2914, 0.3002, 3.7241, 0.0000, 0.0000, 0.7604, 0.0000],
        [0.4358, 0.4809, 0.2055, 5.3614, 0.0000, 0.0000, 0.9326, 0.0000]],
       grad_fn=<ReluBackward0>)


Observe que tivemos que chamar a input_to_hidden_layerativação antes de chamar, hidden_layer_activationpois a saída de input_to_hidden_layeré a entrada para a hidden_layer_activationcamada.

In [57]:
class Neuralnet(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_to_hidden_layer = nn.Linear(2,8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8,1)


    def forward(self, x):
        hidden1 = self.input_to_hidden_layer(x)
        hidden2 = self.hidden_layer_activation(hidden1)
        output = self.hidden_to_output_layer(hidden2)
        return output, hidden2

# Usando um método sequencial para construir uma rede neural

In [58]:
x = [[ 1 , 2 ], [ 3 , 4 ], [ 5 , 6 ], [ 7 , 8 ]] 
y = [[ 3 ], [ 7 ], [ 11 ], [ 15 ]]

In [59]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import Dataset, DataLoader
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [60]:
class MyDataset(Dataset):
    def __init__(self, x, y):
        self.x = torch.tensor(x).float().to(device)
        self.y = torch.tensor(y).float().to(device)
    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]
    def __len__(self): 
        return len(self.x)

In [61]:
ds = MyDataset(x, y)
dl = DataLoader(ds, batch_size=2, shuffle=True)

In [62]:
model = nn.Sequential(nn.Linear(2, 8), nn.ReLU(), nn.Linear(8, 1)).to(device)

In [63]:
# instalando o package torch_summary
!pip install torch_summary

In [64]:
from torchsummary import summary
summary(model, torch.zeros(1,2))

Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 8]                   24
├─ReLU: 1-2                              [-1, 8]                   --
├─Linear: 1-3                            [-1, 1]                   9
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 8]                   24
├─ReLU: 1-2                              [-1, 8]                   --
├─Linear: 1-3                            [-1, 1]                   9
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [65]:
"""A seguir, definimos a função de perda ( loss_func) e o 
otimizador ( opt) e treinamos o modelo"""

loss_func = nn.MSELoss()
from torch.optim import SGD
opt = SGD(model.parameters(), lr = 0.001)
import time
loss_history = []
start = time.time()
for _ in range(50):
    for ix, iy in dl:
        opt.zero_grad()
        loss_value = loss_func(model(ix),iy)
        loss_value.backward()
        opt.step()
        loss_history.append(loss_value)
end = time.time()
print(end - start)

0.6173429489135742


In [66]:
# agora que o modelo está treinado podemos prever os valores
val = [[8 , 9], [10 ,11], [1.5, 2.5]]

In [67]:
model(torch.tensor(val).float().to(device))

tensor([[16.5386],
        [20.2211],
        [ 4.5418]], grad_fn=<AddmmBackward>)

Observe que a saída do código anterior, conforme mostrado no comentário, está próxima do esperado (que é a soma dos valores de entrada).

In [68]:
# salvando
torch.save(model.to('cpu').state_dict(), 'mymodel.pth')

In [69]:
# lendo o arquivo
state_dict = torch.load ('mymodel.pth')

In [70]:
model.load_state_dict (state_dict)

<All keys matched successfully>

Se todos os nomes de peso estiverem presentes no modelo, você receberá uma mensagem dizendo que todas as chaves foram combinadas. Isso significa que podemos carregar nosso modelo do disco, para todos os fins, em qualquer máquina do mundo.

# Attention
Every codes here are book's Moder Computer vision with PyTorch<br>
https://learning.oreilly.com/library/view/modern-computer-vision/9781839213472/f1d61b2c-dbb8-43ac-ac4e-75941daecc4c.xhtml#uuid-7b6ca1ba-20ea-4326-a10f-61c46baa7103 